services:
  panorama-haalcentraal-personen-mock:
      image: ghcr.io/brp-api/personen-mock:2.3.0-latest
      environment:
          - ASPNETCORE_ENVIRONMENT=Release
          - ASPNETCORE_URLS=http://+:5010
      ports:
          - "5010:5010"
      networks:
          - brp-api-network

networks:
      brp-api-network:
          name: brp-api-network